name: Deploy to Azure Kubernetes Service (AKS)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Azure CLI using latest version (fallback)
    - name: Set up Azure CLI
      uses: azure/setup-azurecli@latest

    # Step 3: Login to Azure with Service Principal and debug information
    - name: Login to Azure
      run
