name: Deploy to Azure Kubernetes Service (AKS)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Azure CLI using v2 (explicit version)
    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v2

    # Step 3: Login to Azure with Service Principal and debug information
    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} --debug

    # Step 4: Check Azure CLI version to verify setup
    - name: Check Azure CLI version
      run: az --version
