name: AKS Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Azure CLI using a script (with sudo)
      - name: Install Azure CLI
        run: |
          sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      # Log in to Azure with Service Principal
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group Kubernetes_test --name aks_test

      # Set up kubectl and deploy to AKS
      - name: Deploy to AKS
        run: |
          # Install kubectl if not already present
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --

