name: AKS Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UIx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      # Step 3: Log in to Azure using a service principal
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Step 4: Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group Kubernetes_test --name aks_test

      # Step 5: Deploy the Kubernetes YAML configuration to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/rabbitmq-deployment.yaml  # Apply the Kubernetes YAML from your repository
