name: AKS Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut koden fra GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v2
        with:
          version: '2.0.0'  # optional: specify Azure CLI version if needed


      # Logg inn på Azure med Service Principal
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Hent AKS credentials
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group Kubernetes_test --name aks_test

      # Deploy til AKS ved å bruke kubectl
      - name: Deploy to AKS
        run: kubectl apply -f k8s/deployment.yaml
